import { ModelProviderEnum, ModelProviderType } from '../../types'
import { defineProvider } from '../registry'
import CheaperInference, { CHEAPER_INFERENCE_API_HOST } from './models/cheaper-inference'

export const cheaperInferenceProvider = defineProvider({
  id: ModelProviderEnum.CheaperInference,
  name: 'Cheaper Inference',
  type: ModelProviderType.OpenAI,
  curatedModelIds: [
    'gpt-6-astra',
    'gpt-5.6-sol',
    'gpt-5.6-terra',
    'gpt-5.6-luna',
    'claude-fable-5.1',
    'claude-opus-5',
    'claude-sonnet-5',
    'claude-haiku-4.5',
    'gemini-3.7-flash',
    'gemini-3.1-pro',
    'grok-4.5',
    'deepseek-v4-pro',
    'deepseek-v4.1-flash',
    'kimi-k3',
    'glm-5.3',
    'qwen-3-8-max',
    'minimax-m2.7',
    'gpt-oss-120b',
  ],
  urls: {
    website: 'https://www.cheaperinference.com/',
    apiKey: 'https://www.cheaperinference.com/dashboard/keys',
    docs: 'https://www.cheaperinference.com/docs',
    models: 'https://www.cheaperinference.com/markets',
  },
  defaultSettings: {
    apiHost: CHEAPER_INFERENCE_API_HOST,
    models: [
      {
        modelId: 'gpt-6-astra',
        nickname: 'GPT-6 Astra',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-5.6-sol',
        nickname: 'GPT-5.6 Sol',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-5.6-terra',
        nickname: 'GPT-5.6 Terra',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-5.6-luna',
        nickname: 'GPT-5.6 Luna',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-5.5',
        nickname: 'GPT-5.5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-5.4',
        nickname: 'GPT-5.4',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 131_072,
      },
      {
        modelId: 'gpt-5.4-mini',
        nickname: 'GPT-5.4 Mini',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 400_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'gpt-oss-120b',
        nickname: 'GPT OSS 120B',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 131_072,
      },
      {
        modelId: 'claude-fable-5.1',
        nickname: 'Claude Fable 5.1',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'claude-opus-5',
        nickname: 'Claude Opus 5',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'claude-sonnet-5',
        nickname: 'Claude Sonnet 5',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'claude-opus-4.8',
        nickname: 'Claude Opus 4.8',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'claude-sonnet-4.6',
        nickname: 'Claude Sonnet 4.6',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'claude-haiku-4.5',
        nickname: 'Claude Haiku 4.5',
        capabilities: ['tool_use', 'vision'],
        contextWindow: 200_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'gemini-3.7-flash',
        nickname: 'Gemini 3.7 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'gemini-3.1-pro',
        nickname: 'Gemini 3.1 Pro',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'gemini-3.1-flash-lite',
        nickname: 'Gemini 3.1 Flash Lite',
        capabilities: ['tool_use', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'gemini-2.5-flash',
        nickname: 'Gemini 2.5 Flash',
        capabilities: ['tool_use', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_535,
      },
      {
        modelId: 'grok-4.5',
        nickname: 'Grok 4.5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 500_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'deepseek-v4-pro',
        nickname: 'DeepSeek V4 Pro',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'deepseek-v4.1-flash',
        nickname: 'DeepSeek V4.1 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 384_000,
      },
      {
        modelId: 'kimi-k3',
        nickname: 'Kimi K3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 131_072,
      },
      {
        modelId: 'glm-5.3',
        nickname: 'GLM 5.3',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 131_072,
      },
      {
        modelId: 'glm-5.2',
        nickname: 'GLM 5.2',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 131_072,
      },
      {
        modelId: 'qwen-3-8-max',
        nickname: 'Qwen 3.8 Max',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_000_000,
        maxOutput: 131_072,
      },
      {
        modelId: 'qwen3-6-35b-a3b',
        nickname: 'Qwen3.6 35B A3B',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 262_144,
        maxOutput: 262_144,
      },
      {
        modelId: 'minimax-m2.7',
        nickname: 'MiniMax M2.7',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 198_000,
        maxOutput: 32_768,
      },
    ],
  },
  createModel: (config) => {
    return new CheaperInference(
      {
        apiKey: config.effectiveApiKey,
        model: config.model,
        temperature: config.settings.temperature,
        topP: config.settings.topP,
        maxOutputTokens: config.settings.maxTokens,
        useProxy: config.providerSetting.useProxy,
        stream: config.settings.stream,
      },
      config.dependencies
    )
  },
  getDisplayName: (modelId, providerSettings) => {
    return `Cheaper Inference (${providerSettings?.models?.find((m) => m.modelId === modelId)?.nickname || modelId})`
  },
})
