name: Build and Publish Web App Docker Image

on:
  push:
    tags: [v\d+\.\d+\.\d+, v\d+\.\d+\.\d+-beta\.\d+]
  workflow_dispatch: # Allows manual triggering

env:
  PROJECT_NAME: chatbox-webapp

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build web application
        run: npm run build:web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry-intl.cn-hongkong.aliyuncs.com/iftech-hk
          username: ${{ secrets.ALIYUN_HK_CR_USERNAME }}
          password: ${{ secrets.ALIYUN_HK_CR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry-intl.cn-hongkong.aliyuncs.com/iftech-hk/${{ env.PROJECT_NAME }}
          tags: |
            type=ref,event=tag # Use the Git tag as Docker tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Assuming Dockerfile is in the root
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64 # Match platform from release-web.sh
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify JKDPY
        run: |
          curl ${{ secrets.JKDPY_WEBHOOK_URL }} \
            -u ${{ secrets.JKDPY_WEBHOOK_USERNAME }}:${{ secrets.JKDPY_WEBHOOK_PASSWORD }} \
            -d 'image_name=${{ fromJSON(steps.meta.outputs.json).tags[0] }}&branch_name=${{ github.ref_name }}&service_name=${{ env.PROJECT_NAME }}&commit_message="${{ github.event.head_commit.message }}"'
